name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: outernet-foundation/python-devkit/.github/workflows/check.yml@90141e9fc20af17afa25466c69ce4efb1bce8aba
    with:
      test: false
